name: "new_issues"
description: Новая задача.
title: "[BUG] - <название>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Описание"
      description: Пожалуйста, введите четкое описание вашей проблемы.
      placeholder: Краткое и четкое описание проблемы...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: "URL для воспроизведения"
      description: Отправьте ссылку на видео.
      placeholder: например, https://github.com/USERNAME/REPO-NAME
    validations:
      required: false
  - type: textarea
    id: reprod
    attributes:
      label: "Шаги для воспроизведения"
      description: Пожалуйста, введите четкое описание вашей проблемы.
      value: |
        1. Перейдите на '...'
        2. Нажмите на '....'
        3. Прокрутите вниз до '....'
        4. Увидьте ошибку
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Скриншоты"
      description: Добавьте скриншоты для лучшего объяснения вашей проблемы.
      value: |
        ![ОПИСАНИЕ](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Логи"
      description: Пожалуйста, скопируйте и вставьте любые соответствующие логи. Они будут автоматически отформатированы в код, так что использование обратных кавычек не требуется.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Браузеры"
      description: В каких браузерах вы наблюдаете проблему?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "ОС"
      description: Какая система?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
